[world]
kind = "WorldContract"
class_hash = "0x458d0ce5b14a4844092bdb62050f462d53362304a13febbac6d973691d61be2"
original_class_hash = "0x458d0ce5b14a4844092bdb62050f462d53362304a13febbac6d973691d61be2"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x5c1d201209938c1ac8340c7caeec489060b04dff85399605e58ebc2cdc149f4"
transaction_hash = "0x3b160b37d0ee0f3d51606f047e53add57b6633fc6de50f3b3cafd60153708ee"
block_number = 3
seed = "diamond_pit"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "https://api.cartridge.gg/x/diamond-pit/katana"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x2c24de1c529a154eac885b0b34e8bf1b04f4ce0845b91d1a4fc9aea8c9d71ed"
class_hash = "0x217db2f317155195bfde934f28c20fdee3ca0085403e203d6ad12b1adeeee8b"
original_class_hash = "0x217db2f317155195bfde934f28c20fdee3ca0085403e203d6ad12b1adeeee8b"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/diamond_pit-actions-3fc18067.json"
reads = []
writes = ["ns:diamond_pit"]
init_calldata = []
tag = "diamond_pit-actions"
systems = [
    "hit_block",
    "sync_position",
    "sell_all",
    "upgrade_pickaxe",
    "upgrade_backpack",
    "set_username",
    "rebirth",
    "open_egg",
    "free_daily_credits",
    "generate_world",
]
manifest_name = "diamond_pit-actions-3fc18067"

[[models]]
kind = "DojoModel"
class_hash = "0x474a925eb4e2613d71d04d491ff3643835c68e142115ea6a3f2321ecd9c350f"
original_class_hash = "0x474a925eb4e2613d71d04d491ff3643835c68e142115ea6a3f2321ecd9c350f"
abi = "manifests/dev/deployment/abis/models/diamond_pit-BlocksColumn-766b200b.json"
tag = "diamond_pit-BlocksColumn"
manifest_name = "diamond_pit-BlocksColumn-766b200b"

[[models.members]]
name = "x"
type = "u8"
key = true

[[models.members]]
name = "y"
type = "u8"
key = true

[[models.members]]
name = "z_layer"
type = "u8"
key = true

[[models.members]]
name = "data"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x73fb899e17655effb8f5ab8e389cf2a848d4b1dc2f01345bf94b75e8485d7fd"
original_class_hash = "0x73fb899e17655effb8f5ab8e389cf2a848d4b1dc2f01345bf94b75e8485d7fd"
abi = "manifests/dev/deployment/abis/models/diamond_pit-DailyLeaderboardEntry-1d6ce5ad.json"
tag = "diamond_pit-DailyLeaderboardEntry"
manifest_name = "diamond_pit-DailyLeaderboardEntry-1d6ce5ad"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "day"
type = "u32"
key = true

[[models.members]]
name = "nb_coins_collected"
type = "u64"
key = false

[[models.members]]
name = "nb_blocks_broken"
type = "u16"
key = false

[[models.members]]
name = "nb_hits"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x72a2505ea6a4bc3c6c6773f0fc1144a1d0a5367d6d9cd135d2152446c3988ca"
original_class_hash = "0x72a2505ea6a4bc3c6c6773f0fc1144a1d0a5367d6d9cd135d2152446c3988ca"
abi = "manifests/dev/deployment/abis/models/diamond_pit-PetInventory-6e47b70b.json"
tag = "diamond_pit-PetInventory"
manifest_name = "diamond_pit-PetInventory-6e47b70b"

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "bunnies"
type = "u32"
key = false

[[models.members]]
name = "birds"
type = "u32"
key = false

[[models.members]]
name = "rams"
type = "u32"
key = false

[[models.members]]
name = "chickens"
type = "u32"
key = false

[[models.members]]
name = "rhinos"
type = "u32"
key = false

[[models.members]]
name = "reptiles"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4f2c42a85652e649f70de3221600c24a4e68df8a59b98a9e7cf11b2833e3b3d"
original_class_hash = "0x4f2c42a85652e649f70de3221600c24a4e68df8a59b98a9e7cf11b2833e3b3d"
abi = "manifests/dev/deployment/abis/models/diamond_pit-PlayerInventory-676ae3a3.json"
tag = "diamond_pit-PlayerInventory"
manifest_name = "diamond_pit-PlayerInventory-676ae3a3"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "data"
type = "u64"
key = false

[[models.members]]
name = "coins"
type = "u64"
key = false

[[models.members]]
name = "rebirth_credits"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x71e191e88aad0d5eb241e27c375cd532928e055a9e7787abf6bbe61c6c062d"
original_class_hash = "0x71e191e88aad0d5eb241e27c375cd532928e055a9e7787abf6bbe61c6c062d"
abi = "manifests/dev/deployment/abis/models/diamond_pit-PlayerPosition-69b522e7.json"
tag = "diamond_pit-PlayerPosition"
manifest_name = "diamond_pit-PlayerPosition-69b522e7"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "x"
type = "u32"
key = false

[[models.members]]
name = "y"
type = "u32"
key = false

[[models.members]]
name = "z"
type = "u32"
key = false

[[models.members]]
name = "time"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4c8818b4c78587a8d462eb8dd19f633b485d589905b8aaa7bc2ac8b4e829872"
original_class_hash = "0x4c8818b4c78587a8d462eb8dd19f633b485d589905b8aaa7bc2ac8b4e829872"
abi = "manifests/dev/deployment/abis/models/diamond_pit-PlayerStats-20bc78b8.json"
tag = "diamond_pit-PlayerStats"
manifest_name = "diamond_pit-PlayerStats-20bc78b8"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "backpack_level"
type = "u8"
key = false

[[models.members]]
name = "pickaxe_level"
type = "u8"
key = false

[[models.members]]
name = "rebirth"
type = "u16"
key = false

[[models.members]]
name = "next_daily_coin"
type = "u64"
key = false
