[world]
kind = "WorldContract"
class_hash = "0x458d0ce5b14a4844092bdb62050f462d53362304a13febbac6d973691d61be2"
original_class_hash = "0x458d0ce5b14a4844092bdb62050f462d53362304a13febbac6d973691d61be2"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x34d4e2fcecd511a3286e6acc3e0108ff5d6b7e9290876f988a76163ade950b2"
transaction_hash = "0x3c006a7d1fa97ed7ac6b167aafa75044a89375f55449951ea6ad16d34d17dba"
block_number = 3
seed = "dojo_examples"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "https://api.cartridge.gg/x/diamond-pit/katana"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x3ef05fbe904cf834c4bf94a454a9d86d553089cfe614785cb60b8c559a2dc68"
class_hash = "0x528f0e7804088e0c66e6053525d7a3f3cc14e913199a8371feccd7886d7d1e1"
original_class_hash = "0x528f0e7804088e0c66e6053525d7a3f3cc14e913199a8371feccd7886d7d1e1"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/dojo_examples-actions-40b6994c.json"
reads = []
writes = ["ns:dojo_examples"]
init_calldata = []
tag = "dojo_examples-actions"
systems = [
    "hit_block",
    "sell_all",
    "upgrade_pickaxe",
    "upgrade_backpack",
    "inspect_block",
    "generate_world",
]
manifest_name = "dojo_examples-actions-40b6994c"

[[models]]
kind = "DojoModel"
class_hash = "0x3c3e1584204c7c104a494586730b3f447b161b2d82af79c26a523b3264089af"
original_class_hash = "0x3c3e1584204c7c104a494586730b3f447b161b2d82af79c26a523b3264089af"
abi = "manifests/dev/deployment/abis/models/dojo_examples-BlocksColumn-7d5ae84e.json"
tag = "dojo_examples-BlocksColumn"
manifest_name = "dojo_examples-BlocksColumn-7d5ae84e"

[[models.members]]
name = "x"
type = "u8"
key = true

[[models.members]]
name = "y"
type = "u8"
key = true

[[models.members]]
name = "z_layer"
type = "u8"
key = true

[[models.members]]
name = "data"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2646990b7c05280300583f2a63f6e51562e55c19551821860c189b7a437dcd2"
original_class_hash = "0x2646990b7c05280300583f2a63f6e51562e55c19551821860c189b7a437dcd2"
abi = "manifests/dev/deployment/abis/models/dojo_examples-DailyLeaderboardEntry-2a419e62.json"
tag = "dojo_examples-DailyLeaderboardEntry"
manifest_name = "dojo_examples-DailyLeaderboardEntry-2a419e62"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "day"
type = "u32"
key = true

[[models.members]]
name = "nb_coins_collected"
type = "u64"
key = false

[[models.members]]
name = "nb_blocks_broken"
type = "u16"
key = false

[[models.members]]
name = "nb_hits"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3a060ac88af66ca77c843f465798fb7e128a9373e4b8dcc16bae43fd4fd05ee"
original_class_hash = "0x3a060ac88af66ca77c843f465798fb7e128a9373e4b8dcc16bae43fd4fd05ee"
abi = "manifests/dev/deployment/abis/models/dojo_examples-PlayerInventory-16f11255.json"
tag = "dojo_examples-PlayerInventory"
manifest_name = "dojo_examples-PlayerInventory-16f11255"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "data"
type = "u64"
key = false

[[models.members]]
name = "coins"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x505866fd7cdf4ed7e22365458b2f121f8bde1af832a45ad0f5f45493c585ffb"
original_class_hash = "0x505866fd7cdf4ed7e22365458b2f121f8bde1af832a45ad0f5f45493c585ffb"
abi = "manifests/dev/deployment/abis/models/dojo_examples-PlayerStats-1212a11b.json"
tag = "dojo_examples-PlayerStats"
manifest_name = "dojo_examples-PlayerStats-1212a11b"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "backpack_level"
type = "u8"
key = false

[[models.members]]
name = "pickaxe_level"
type = "u8"
key = false

[[models.members]]
name = "rebirth"
type = "u16"
key = false
