[world]
kind = "WorldContract"
class_hash = "0x458d0ce5b14a4844092bdb62050f462d53362304a13febbac6d973691d61be2"
original_class_hash = "0x458d0ce5b14a4844092bdb62050f462d53362304a13febbac6d973691d61be2"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x5c1d201209938c1ac8340c7caeec489060b04dff85399605e58ebc2cdc149f4"
transaction_hash = "0x1230d4b7e499d09c441c85a1d8cfec87180b6b535e5356bb14d6b490e1c906c"
block_number = 54
seed = "diamond_pit"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "https://api.cartridge.gg/x/diamond-pit/katana"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x2c24de1c529a154eac885b0b34e8bf1b04f4ce0845b91d1a4fc9aea8c9d71ed"
class_hash = "0x6a694fa7a22bf1b8717c69c4783e8659aa72b4369f5345ad9d6c4c2cc3e8eba"
original_class_hash = "0x6a694fa7a22bf1b8717c69c4783e8659aa72b4369f5345ad9d6c4c2cc3e8eba"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/diamond_pit-actions-3fc18067.json"
reads = []
writes = ["ns:diamond_pit"]
init_calldata = []
tag = "diamond_pit-actions"
systems = [
    "hit_block",
    "sell_all",
    "upgrade_pickaxe",
    "upgrade_backpack",
    "inspect_block",
    "generate_world",
]
manifest_name = "diamond_pit-actions-3fc18067"

[[models]]
kind = "DojoModel"
class_hash = "0x474a925eb4e2613d71d04d491ff3643835c68e142115ea6a3f2321ecd9c350f"
original_class_hash = "0x474a925eb4e2613d71d04d491ff3643835c68e142115ea6a3f2321ecd9c350f"
abi = "manifests/dev/deployment/abis/models/diamond_pit-BlocksColumn-766b200b.json"
tag = "diamond_pit-BlocksColumn"
manifest_name = "diamond_pit-BlocksColumn-766b200b"

[[models.members]]
name = "x"
type = "u8"
key = true

[[models.members]]
name = "y"
type = "u8"
key = true

[[models.members]]
name = "z_layer"
type = "u8"
key = true

[[models.members]]
name = "data"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x73fb899e17655effb8f5ab8e389cf2a848d4b1dc2f01345bf94b75e8485d7fd"
original_class_hash = "0x73fb899e17655effb8f5ab8e389cf2a848d4b1dc2f01345bf94b75e8485d7fd"
abi = "manifests/dev/deployment/abis/models/diamond_pit-DailyLeaderboardEntry-1d6ce5ad.json"
tag = "diamond_pit-DailyLeaderboardEntry"
manifest_name = "diamond_pit-DailyLeaderboardEntry-1d6ce5ad"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "day"
type = "u32"
key = true

[[models.members]]
name = "nb_coins_collected"
type = "u64"
key = false

[[models.members]]
name = "nb_blocks_broken"
type = "u16"
key = false

[[models.members]]
name = "nb_hits"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4f71913a0e7dfe072368531b1ad324abbdeac558585bd72a838d900fd35873c"
original_class_hash = "0x4f71913a0e7dfe072368531b1ad324abbdeac558585bd72a838d900fd35873c"
abi = "manifests/dev/deployment/abis/models/diamond_pit-PlayerInventory-676ae3a3.json"
tag = "diamond_pit-PlayerInventory"
manifest_name = "diamond_pit-PlayerInventory-676ae3a3"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "data"
type = "u64"
key = false

[[models.members]]
name = "coins"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x70c3e42817e21cd81aab9674860ce73f19bed83f82bec7f31ba7b154d4cb621"
original_class_hash = "0x70c3e42817e21cd81aab9674860ce73f19bed83f82bec7f31ba7b154d4cb621"
abi = "manifests/dev/deployment/abis/models/diamond_pit-PlayerStats-20bc78b8.json"
tag = "diamond_pit-PlayerStats"
manifest_name = "diamond_pit-PlayerStats-20bc78b8"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "backpack_level"
type = "u8"
key = false

[[models.members]]
name = "pickaxe_level"
type = "u8"
key = false

[[models.members]]
name = "rebirth"
type = "u16"
key = false
