kind = "DojoModel"
class_hash = "0x4f71913a0e7dfe072368531b1ad324abbdeac558585bd72a838d900fd35873c"
original_class_hash = "0x4f71913a0e7dfe072368531b1ad324abbdeac558585bd72a838d900fd35873c"
abi = "manifests/dev/base/abis/models/diamond_pit-PlayerInventory-676ae3a3.json"
tag = "diamond_pit-PlayerInventory"
manifest_name = "diamond_pit-PlayerInventory-676ae3a3"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "data"
type = "u64"
key = false

[[members]]
name = "coins"
type = "u64"
key = false
