kind = "DojoModel"
class_hash = "0xe615c3b06e36ab577e3419fbf8c7cdab6f50d8097dfeab9aa1a9735b437836"
original_class_hash = "0xe615c3b06e36ab577e3419fbf8c7cdab6f50d8097dfeab9aa1a9735b437836"
abi = "manifests/dev/base/abis/models/diamond_pit-PlayerStats-20bc78b8.json"
tag = "diamond_pit-PlayerStats"
manifest_name = "diamond_pit-PlayerStats-20bc78b8"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "backpack_level"
type = "u8"
key = false

[[members]]
name = "pickaxe_level"
type = "u8"
key = false

[[members]]
name = "rebirth"
type = "u16"
key = false
