kind = "DojoModel"
class_hash = "0x3c3e1584204c7c104a494586730b3f447b161b2d82af79c26a523b3264089af"
original_class_hash = "0x3c3e1584204c7c104a494586730b3f447b161b2d82af79c26a523b3264089af"
abi = "manifests/dev/base/abis/models/dojo_examples-BlocksColumn-7d5ae84e.json"
tag = "dojo_examples-BlocksColumn"
manifest_name = "dojo_examples-BlocksColumn-7d5ae84e"

[[members]]
name = "x"
type = "u8"
key = true

[[members]]
name = "y"
type = "u8"
key = true

[[members]]
name = "z_layer"
type = "u8"
key = true

[[members]]
name = "data"
type = "u128"
key = false
