kind = "DojoModel"
class_hash = "0x2646990b7c05280300583f2a63f6e51562e55c19551821860c189b7a437dcd2"
original_class_hash = "0x2646990b7c05280300583f2a63f6e51562e55c19551821860c189b7a437dcd2"
abi = "manifests/dev/base/abis/models/dojo_examples-DailyLeaderboardEntry-2a419e62.json"
tag = "dojo_examples-DailyLeaderboardEntry"
manifest_name = "dojo_examples-DailyLeaderboardEntry-2a419e62"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "day"
type = "u32"
key = true

[[members]]
name = "nb_coins_collected"
type = "u64"
key = false

[[members]]
name = "nb_blocks_broken"
type = "u16"
key = false

[[members]]
name = "nb_hits"
type = "u16"
key = false
