[package]
cairo-version = "=2.7.0"
name = "diamond_pit"
version = "1.0.0-alpha.6"
# Use the prelude with the less imports as possible
# from corelib.
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-alpha.6" }

[[target.dojo]]