kind = "DojoContract"
class_hash = "0x273a513f89c9b513780a5c69c9a7ee8a0b83386d0cdd8455de4ea7fab9dda64"
original_class_hash = "0x273a513f89c9b513780a5c69c9a7ee8a0b83386d0cdd8455de4ea7fab9dda64"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/diamond_pit-actions-3fc18067.json"
reads = []
writes = []
init_calldata = []
tag = "diamond_pit-actions"
systems = [
    "hit_block",
    "sync_position",
    "sell_all",
    "upgrade_pickaxe",
    "upgrade_backpack",
    "set_username",
    "rebirth",
    "open_egg",
    "free_daily_credits",
    "generate_world",
]
manifest_name = "diamond_pit-actions-3fc18067"
