kind = "DojoContract"
class_hash = "0x723027f530d9258c65a2bee77fea53f0a1a979b687972adf03231e9cf86d78d"
original_class_hash = "0x723027f530d9258c65a2bee77fea53f0a1a979b687972adf03231e9cf86d78d"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/diamond_pit-actions-3fc18067.json"
reads = []
writes = []
init_calldata = []
tag = "diamond_pit-actions"
systems = [
    "hit_block",
    "sell_all",
    "upgrade_pickaxe",
    "upgrade_backpack",
    "inspect_block",
    "generate_world",
]
manifest_name = "diamond_pit-actions-3fc18067"
