kind = "DojoContract"
class_hash = "0x6a694fa7a22bf1b8717c69c4783e8659aa72b4369f5345ad9d6c4c2cc3e8eba"
original_class_hash = "0x6a694fa7a22bf1b8717c69c4783e8659aa72b4369f5345ad9d6c4c2cc3e8eba"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/diamond_pit-actions-3fc18067.json"
reads = []
writes = []
init_calldata = []
tag = "diamond_pit-actions"
systems = [
    "hit_block",
    "sell_all",
    "upgrade_pickaxe",
    "upgrade_backpack",
    "inspect_block",
    "generate_world",
]
manifest_name = "diamond_pit-actions-3fc18067"
