kind = "DojoContract"
class_hash = "0x1cd19b47114431928a460ef4cda9b2c6cbab728f685192f9a380704af215657"
original_class_hash = "0x1cd19b47114431928a460ef4cda9b2c6cbab728f685192f9a380704af215657"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/diamond_pit-actions-3fc18067.json"
reads = []
writes = []
init_calldata = []
tag = "diamond_pit-actions"
systems = [
    "hit_block",
    "sync_position",
    "sell_all",
    "upgrade_pickaxe",
    "upgrade_backpack",
    "set_username",
    "generate_world",
]
manifest_name = "diamond_pit-actions-3fc18067"
