kind = "DojoContract"
class_hash = "0x528f0e7804088e0c66e6053525d7a3f3cc14e913199a8371feccd7886d7d1e1"
original_class_hash = "0x528f0e7804088e0c66e6053525d7a3f3cc14e913199a8371feccd7886d7d1e1"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_examples-actions-40b6994c.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_examples-actions"
systems = [
    "hit_block",
    "sell_all",
    "upgrade_pickaxe",
    "upgrade_backpack",
    "inspect_block",
    "generate_world",
]
manifest_name = "dojo_examples-actions-40b6994c"
